### ISSUE TITLE
log4j problem

### ISSUE THREAD

**Issue by spyroskantarelis** [jimjonesbr/musicowl#4]
File            : musicxml/metadata-file/elgar_cello_concerto_op.85.xml

log4j:WARN No appenders could be found for logger (Converter).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
java.io.FileNotFoundException:
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at java.io.FileOutputStream.<init>(Unknown Source)
        at de.wwu.music2rdf.converter.MusicXML2RDF.createRDF(MusicXML2RDF.java:1358)
        at de.wwu.music2rdf.converter.MusicXML2RDF.parseMusicXML(MusicXML2RDF.java:1486)
        at de.wwu.music2rdf.converter.Converter.main(Converter.java:62)

**Comment by jimjonesbr** [comment]
Problem solved in 1.3.8
